# A file containing all external dependencies
# TODO: originally autogenerated by an external dependencies updater, consider doing that

all = {
    "git_repositories": {
        # Add git repositories here
    },
    "new_git_repositories": {
        "k8s-config-connector": {
            "doc": "Snapped from 'v1.88.0'",
            "purl": "pkg:github/googlecloudplatform/k8s-config-connector@v1.88.0",
            "version": "v1.88.0",
            "expansion": {
                "name": "k8s-config-connector",
                "commit": "730c4bba8ec7dbeca5297b244ef1a62cddca1fb4",
                "remote": "https://github.com/GoogleCloudPlatform/k8s-config-connector.git",
                "shallow_since": "",
                "build_file_content": "exports_files(['install-bundles/install-bundle-workload-identity/crds.yaml'])",
            },
        },
    },
    "github_archives": {
        # Add github archives here
    },
    "container_pulls": {
        # Add container pulls here
    },
    "java": {
        "jre": {
            "major_version": 18,
            "archive_name": "zulu18.30.11-ca-jre18.0.1-linux_x64",
            "url": "https://cdn.azul.com/zulu/bin/zulu18.30.11-ca-jre18.0.1-linux_x64.tar.gz",
            "sha256": "35e67c910dc03d02ea698af19225741a56df9a86c1717fc13caaed641c6ec682",
        },
        "jdk": {
            "major_version": 18,
            "archive_name": "zulu18.30.11-ca-jdk18.0.1-linux_x64",
            "url": "https://cdn.azul.com/zulu/bin/zulu18.30.11-ca-jdk18.0.1-linux_x64.tar.gz",
            "sha256": "975417f06145d3af06cb9b83fee2032f80fdae80766b1397157527c125bf00c1",
        },
    },
    "go": {
        "version": "1.18.3",
    },
    "gcs_expansions": {
        # Add gcs expansions here
    },
}
