# Note: autogenerated from cleanliness.ExternalDepUpdater

all = {
    "git_repositories": {
        "bazel": {
            "doc": "Snapped from '5.2.0'",
            "purl": "pkg:github/bazelbuild/bazel@5.2.0",
            "version": "5.2.0",
            "expansion": {
                "name": "bazel",
                "commit": "2e8458b7810eab7829fc7d28af5c45b9af91ed7c",
                "remote": "https://github.com/bazelbuild/bazel.git",
                "shallow_since": "",
            },
        },
        "bazel_gazelle": {
            "doc": "Snapped from 'v0.25.0'",
            "purl": "pkg:github/bazelbuild/bazel-gazelle@v0.25.0",
            "version": "v0.25.0",
            "expansion": {
                "name": "bazel_gazelle",
                "commit": "6473a8bc7acc1e404fe238c23decf7f4f035a265",
                "remote": "https://github.com/bazelbuild/bazel-gazelle.git",
                "shallow_since": "",
            },
        },
        "bazel_skylib": {
            "doc": "Snapped from '1.2.1'",
            "purl": "pkg:github/bazelbuild/bazel-skylib@1.2.1",
            "version": "1.2.1",
            "expansion": {
                "name": "bazel_skylib",
                "commit": "ee67264452174896741824ed25ade0f6d58ca642",
                "remote": "https://github.com/bazelbuild/bazel-skylib.git",
                "shallow_since": "",
            },
        },
        "build_bazel_rules_nodejs": {
            "doc": "Snapped from '4.4.1'",
            "purl": "pkg:github/bazelbuild/rules_nodejs@4.4.1",
            "version": "4.4.1",
            "expansion": {
                "name": "build_bazel_rules_nodejs",
                "commit": "7557d3c09edf1aa6c4abafc4616a3b008a19a547",
                "remote": "https://github.com/bazelbuild/rules_nodejs.git",
                "shallow_since": "",
            },
        },
        "com_github_bazelbuild_buildtools": {
            "doc": "Snapped from '5.1.0'",
            "purl": "pkg:github/bazelbuild/buildtools@5.1.0",
            "version": "5.1.0",
            "expansion": {
                "name": "com_github_bazelbuild_buildtools",
                "commit": "c802c3b06ba674e8a76d04c0677d153ab9f660c9",
                "remote": "https://github.com/bazelbuild/buildtools.git",
                "shallow_since": "",
            },
        },
        "io_bazel_rules_avro": {
            "doc": "Snapped from 'master branch'",
            "purl": "pkg:github/chenrui333/rules_avro@master%20branch",
            "version": "master branch",
            "expansion": {
                "name": "io_bazel_rules_avro",
                "commit": "eee228b5035b098d4b2dc837cdcac8171c56a8b0",
                "remote": "https://github.com/chenrui333/rules_avro.git",
                "shallow_since": "",
            },
        },
        "io_bazel_rules_docker": {
            "doc": "Snapped from 'v0.23.0'",
            "purl": "pkg:github/bazelbuild/rules_docker@v0.23.0",
            "version": "v0.23.0",
            "expansion": {
                "name": "io_bazel_rules_docker",
                "commit": "c27194b35f56a1bea6e37f58e549230823653dc3",
                "remote": "https://github.com/bazelbuild/rules_docker.git",
                "shallow_since": "",
            },
        },
        "io_bazel_stardoc": {
            "doc": "Snapped from '0.5.1'",
            "purl": "pkg:github/bazelbuild/stardoc@0.5.1",
            "version": "0.5.1",
            "expansion": {
                "name": "io_bazel_stardoc",
                "commit": "4b7da9f973fd09abafa428826b86a695618bb564",
                "remote": "https://github.com/bazelbuild/stardoc.git",
                "shallow_since": "",
            },
        },
        "rules_java": {
            "doc": "Snapped from '5.0.0'",
            "purl": "pkg:github/bazelbuild/rules_java@5.0.0",
            "version": "5.0.0",
            "expansion": {
                "name": "rules_java",
                "commit": "7a3c520737581f13691ad94a0f798a3518d869d1",
                "remote": "https://github.com/bazelbuild/rules_java.git",
                "shallow_since": "",
            },
        },
        "rules_jvm_external": {
            "doc": "Snapped from '4.2'",
            "purl": "pkg:github/bazelbuild/rules_jvm_external@4.2",
            "version": "4.2",
            "expansion": {
                "name": "rules_jvm_external",
                "commit": "3f1fb4056207b253542d00ae55736eb613e44731",
                "remote": "https://github.com/bazelbuild/rules_jvm_external.git",
                "shallow_since": "",
            },
        },
    },
    "new_git_repositories": {
        "autoneg-controller": {
            "doc": "Snapped from 'v0.9.6'",
            "purl": "pkg:github/googlecloudplatform/gke-autoneg-controller@v0.9.6",
            "version": "v0.9.6",
            "expansion": {
                "name": "autoneg-controller",
                "commit": "d8065c92ba4d86c44d221a59dedb5d676a412ccf",
                "remote": "https://github.com/GoogleCloudPlatform/gke-autoneg-controller.git",
                "shallow_since": "",
                "build_file_content": "exports_files(['deploy/autoneg.yaml'])",
            },
        },
        "jetbrains-projector-docker": {
            "doc": "Snapped from 'master branch'",
            "purl": "pkg:github/jetbrains/projector-docker@master%20branch",
            "version": "master branch",
            "expansion": {
                "name": "jetbrains-projector-docker",
                "commit": "656bf07619253ba1cda9aa0c60fb03f9698944e3",
                "remote": "https://github.com/JetBrains/projector-docker.git",
                "shallow_since": "",
                "build_file_content": "exports_files([\"static/ide-projector-launcher.sh\"])\n\nfilegroup(\n    name = \"files\",\n    srcs = glob([\"**/*\"]),\n    visibility = [\"//visibility:public\"],\n)\n\nfilegroup(\n    name = \"static\",\n    srcs = glob([\"**/*\"]),\n    visibility = [\"//visibility:public\"],\n)\n",
            },
        },
        "k8s-config-connector": {
            "doc": "Snapped from 'v1.88.0'",
            "purl": "pkg:github/googlecloudplatform/k8s-config-connector@v1.88.0",
            "version": "v1.88.0",
            "expansion": {
                "name": "k8s-config-connector",
                "commit": "730c4bba8ec7dbeca5297b244ef1a62cddca1fb4",
                "remote": "https://github.com/GoogleCloudPlatform/k8s-config-connector.git",
                "shallow_since": "",
                "build_file_content": "exports_files(['install-bundles/install-bundle-workload-identity/crds.yaml'])",
            },
        },
    },
    "github_archives": {
        "bazel_toolchains": {
            "doc": "Snapped from 'v5.1.1'",
            "purl": "pkg:github/bazelbuild/bazel-toolchains@v5.1.1",
            "version": "v5.1.1",
            "expansion": {
                "name": "bazel_toolchains",
                "build_file_content": "",
                "kwargs": {
                    "strip_prefix": "bazel-toolchains-5.1.1",
                },
                "sha256": "e52789d4e89c3e2dc0e3446a9684626a626b6bec3fde787d70bae37c6ebcc47f",
                "urls": ["https://github.com/bazelbuild/bazel-toolchains/archive/v5.1.1.tar.gz"],
            },
        },
        "com_github_twbs_bootstrap": {
            "doc": "Snapped from 'v5.1.3'",
            "purl": "pkg:github/twbs/bootstrap@v5.1.3",
            "version": "v5.1.3",
            "expansion": {
                "name": "com_github_twbs_bootstrap",
                "build_file_content": "exports_files(['css/bootstrap.min.css', 'js/bootstrap.min.js'])",
                "kwargs": {
                    "strip_prefix": "bootstrap-5.1.3-dist",
                },
                "sha256": "bdec29db50ec8d1ecccb702022b823df0a333e105814c264b321bd518b89c721",
                "urls": ["https://github.com/twbs/bootstrap/releases/download/v5.1.3/bootstrap-5.1.3-dist.zip"],
            },
        },
        "io_bazel_rules_go": {
            "doc": "Snapped from 'v0.29.0'",
            "purl": "pkg:github/bazelbuild/rules_go@v0.29.0",
            "version": "v0.29.0",
            "expansion": {
                "name": "io_bazel_rules_go",
                "build_file_content": "",
                "kwargs": {
                    "patches": ["//:go/patches/io_bazel_rules_go/service-registrar.diff"],
                },
                "sha256": "2b1641428dff9018f9e85c0384f03ec6c10660d935b750e3fa1492a281a53b0f",
                "urls": ["https://github.com/bazelbuild/rules_go/releases/download/v0.29.0/rules_go-v0.29.0.zip"],
            },
        },
        "k9s": {
            "doc": "Snapped from 'v0.25.18'",
            "purl": "pkg:github/derailed/k9s@v0.25.18",
            "version": "v0.25.18",
            "expansion": {
                "name": "k9s",
                "build_file_content": "filegroup(\n    name = \"k9s-binary\",\n    srcs = [\"k9s\"],\n    visibility = [\"//visibility:public\"],\n)\n",
                "kwargs": {},
                "sha256": "d288aacc368ab6b243fc9e7ecd17b53fa34a813509c2dc3023171085db83cf9d",
                "urls": ["https://github.com/derailed/k9s/releases/download/v0.25.18/k9s_Linux_x86_64.tar.gz"],
            },
        },
        "kubeconform": {
            "doc": "Snapped from 'v0.4.13'",
            "purl": "pkg:github/yannh/kubeconform@v0.4.13",
            "version": "v0.4.13",
            "expansion": {
                "name": "kubeconform",
                "build_file_content": "exports_files(['kubeconform'])",
                "kwargs": {},
                "sha256": "690ff27e79d634d98fe2597df522237c9eb7ad2f6ed207dd67b68c74e9f1ba9c",
                "urls": ["https://github.com/yannh/kubeconform/releases/download/v0.4.13/kubeconform-linux-amd64.tar.gz"],
            },
        },
        "prometheus-engine": {
            "doc": "Snapped from 'v0.4.0'",
            "purl": "pkg:github/googlecloudplatform/prometheus-engine@v0.4.0",
            "version": "v0.4.0",
            "expansion": {
                "name": "prometheus-engine",
                "build_file_content": "filegroup(\n    name = \"yamls\",\n    srcs = glob([\"manifests/*.yaml\"]),\n    visibility = [\"//visibility:public\"],\n)\n",
                "kwargs": {
                    "strip_prefix": "prometheus-engine-0.4.0",
                },
                "sha256": "e2fd0cd2c7b849822b31c472f43982a0d3f8bbf246d7b753cddcf3ad420fbe44",
                "urls": ["https://github.com/GoogleCloudPlatform/prometheus-engine/archive/v0.4.0.tar.gz"],
            },
        },
        "rules_pkg": {
            "doc": "Snapped from '0.7.0'",
            "purl": "pkg:github/bazelbuild/rules_pkg@0.7.0",
            "version": "0.7.0",
            "expansion": {
                "name": "rules_pkg",
                "build_file_content": "",
                "kwargs": {
                    "strip_prefix": "rules_pkg-0.7.0",
                },
                "sha256": "e110311d898c1ff35f39829ae3ec56e39c0ef92eb44de74418982a114f51e132",
                "urls": ["https://github.com/bazelbuild/rules_pkg/archive/0.7.0.tar.gz"],
            },
        },
    },
    "container_pulls": {
        "alertmanager": {
            "doc": "Snapped from 'v0.24.0'",
            "purl": "pkg:docker/prom/alertmanager@v0.24.0?repository_url=docker.io",
            "version": "v0.24.0",
            "expansion": {
                "name": "alertmanager",
                "digest": "sha256:b1ba90841a82ea24d79d4e6255b96025a9e89275bec0fae87d75a5959461971e",
                "registry": "docker.io",
                "repository": "prom/alertmanager",
            },
        },
        "alpine-base": {
            "doc": "Snapped from '3.16.0'",
            "purl": "pkg:docker/alpine/alpine@3.16.0?repository_url=docker.io",
            "version": "3.16.0",
            "expansion": {
                "name": "alpine-base",
                "digest": "sha256:4ff3ca91275773af45cb4b0834e12b7eb47d1c18f770a0b151381cd227f4c253",
                "registry": "docker.io",
                "repository": "alpine",
            },
        },
        "cloud-sdk-alpine": {
            "doc": "Snapped from '390.0.0-alpine'",
            "purl": "pkg:docker/google.com/cloudsdktool%2Fcloud-sdk@390.0.0-alpine?repository_url=gcr.io",
            "version": "390.0.0-alpine",
            "expansion": {
                "name": "cloud-sdk-alpine",
                "digest": "sha256:50e9805446e2990a947fbaedbee01785b3648e23089c5248414990e25c759d52",
                "registry": "gcr.io",
                "repository": "google.com/cloudsdktool/cloud-sdk",
            },
        },
        "cloudshell-base": {
            "doc": "Snapped from '390.0.0'",
            "purl": "pkg:docker/google.com/cloudsdktool%2Fcloud-sdk@390.0.0?repository_url=gcr.io",
            "version": "390.0.0",
            "expansion": {
                "name": "cloudshell-base",
                "digest": "sha256:4327db67127b34c4e842cd858748624970bb6c290fff3c43a2be6ad7a4a23443",
                "registry": "gcr.io",
                "repository": "google.com/cloudsdktool/cloud-sdk",
            },
        },
        "code-server-cloudshell-base": {
            "doc": "Snapped from 'latest'",
            "purl": "pkg:docker/google-appengine/debian9@latest?repository_url=gcr.io",
            "version": "latest",
            "expansion": {
                "name": "code-server-cloudshell-base",
                "digest": "sha256:31045141d40e75e408376d3ff43a3c9a4cc6f60cb8affbc58e6903ef277fe0e1",
                "registry": "gcr.io",
                "repository": "google-appengine/debian9",
            },
        },
        "debian": {
            "doc": "Snapped from 'latest'",
            "purl": "pkg:docker/cloud-marketplace/google%2Fdebian11@latest?repository_url=gcr.io",
            "version": "latest",
            "expansion": {
                "name": "debian",
                "digest": "sha256:69e2789c9f3d28c6a0f13b25062c240ee7772be1f5e6d41bb4680b63eae6b304",
                "registry": "gcr.io",
                "repository": "cloud-marketplace/google/debian11",
            },
        },
        "dind": {
            "doc": "Snapped from '20.10.9-dind'",
            "purl": "pkg:docker/docker/docker@20.10.9-dind?repository_url=docker.io",
            "version": "20.10.9-dind",
            "expansion": {
                "name": "dind",
                "digest": "sha256:24628ded7711e48db56af875236ac30a8950305ac461332955b3375ac5a87e1a",
                "registry": "docker.io",
                "repository": "docker",
            },
        },
        "envoy": {
            "doc": "Snapped from 'v1.21.1'",
            "purl": "pkg:docker/envoyproxy/envoy@v1.21.1?repository_url=docker.io",
            "version": "v1.21.1",
            "expansion": {
                "name": "envoy",
                "digest": "sha256:9e6ea1a08e8b72fc51b16261fe8033f7618b670b0c1c18e5b092191850c0747a",
                "registry": "docker.io",
                "repository": "envoyproxy/envoy",
            },
        },
        "gke-sample-app": {
            "doc": "Snapped from '2.0'",
            "purl": "pkg:docker/google-samples/hello-app@2.0?repository_url=gcr.io",
            "version": "2.0",
            "expansion": {
                "name": "gke-sample-app",
                "digest": "sha256:2b0febe1b9bd01739999853380b1a939e8102fd0dc5e2ff1fc6892c4557d52b9",
                "registry": "gcr.io",
                "repository": "google-samples/hello-app",
            },
        },
        "grafana": {
            "doc": "Snapped from '7.5.15'",
            "purl": "pkg:docker/grafana/grafana@7.5.15?repository_url=docker.io",
            "version": "7.5.15",
            "expansion": {
                "name": "grafana",
                "digest": "sha256:8e6fe7907f8e5c5547bee5e3e8be8165144d86ad98581d6d092044aa5f805c39",
                "registry": "docker.io",
                "repository": "grafana/grafana",
            },
        },
        "nginx_alpine": {
            "doc": "Snapped from '1.22.0-alpine'",
            "purl": "pkg:docker/nginx/nginx@1.22.0-alpine?repository_url=docker.io",
            "version": "1.22.0-alpine",
            "expansion": {
                "name": "nginx_alpine",
                "digest": "sha256:e012f7b78c91f50a8a98bec1b707e454f783c5cbc5a8caeaadce60b3d143b70f",
                "registry": "docker.io",
                "repository": "nginx",
            },
        },
        "opa-agent": {
            "doc": "Snapped from '0.41.0'",
            "purl": "pkg:docker/openpolicyagent/opa@0.41.0?repository_url=docker.io",
            "version": "0.41.0",
            "expansion": {
                "name": "opa-agent",
                "digest": "sha256:c34704b307b3114f4c5d743c17b04fc663154245c7e8668eb9dcd49f2b00ca05",
                "registry": "docker.io",
                "repository": "openpolicyagent/opa",
            },
        },
        "opa-envoy": {
            "doc": "Snapped from '0.41.0-envoy'",
            "purl": "pkg:docker/openpolicyagent/opa@0.41.0-envoy?repository_url=docker.io",
            "version": "0.41.0-envoy",
            "expansion": {
                "name": "opa-envoy",
                "digest": "sha256:5b5eea4a7d6e6245b7670ef260cb5f6d7e0eb8253af306d606a1035c16e42340",
                "registry": "docker.io",
                "repository": "openpolicyagent/opa",
            },
        },
        "opa-istio-plugin": {
            "doc": "Snapped from '0.41.0-istio'",
            "purl": "pkg:docker/openpolicyagent/opa@0.41.0-istio?repository_url=docker.io",
            "version": "0.41.0-istio",
            "expansion": {
                "name": "opa-istio-plugin",
                "digest": "sha256:5b5eea4a7d6e6245b7670ef260cb5f6d7e0eb8253af306d606a1035c16e42340",
                "registry": "docker.io",
                "repository": "openpolicyagent/opa",
            },
        },
        "opa-proxy-init": {
            "doc": "Snapped from 'v7'",
            "purl": "pkg:docker/openpolicyagent/proxy_init@v7?repository_url=docker.io",
            "version": "v7",
            "expansion": {
                "name": "opa-proxy-init",
                "digest": "sha256:6281ef1379fdbd9980848f37938d38e3d49ecfb064e0f9da4adf0ad8c5bd7526",
                "registry": "docker.io",
                "repository": "openpolicyagent/proxy_init",
            },
        },
        "prometheus-frontend": {
            "doc": "Snapped from 'v0.4.0-gke.0'",
            "purl": "pkg:docker/prometheus-engine/frontend@v0.4.0-gke.0?repository_url=gke.gcr.io",
            "version": "v0.4.0-gke.0",
            "expansion": {
                "name": "prometheus-frontend",
                "digest": "sha256:6d9832ec3b101a14d0d5b883816f34bc6f8f8b5b10a26a593ce47ebb3316cc69",
                "registry": "gke.gcr.io",
                "repository": "prometheus-engine/frontend",
            },
        },
    },
    "java": {
        "jre": {
            "major_version": 18,
            "archive_name": "zulu18.30.11-ca-jre18.0.1-linux_x64",
            "url": "https://cdn.azul.com/zulu/bin/zulu18.30.11-ca-jre18.0.1-linux_x64.tar.gz",
            "sha256": "35e67c910dc03d02ea698af19225741a56df9a86c1717fc13caaed641c6ec682",
        },
        "jdk": {
            "major_version": 18,
            "archive_name": "zulu18.30.11-ca-jdk18.0.1-linux_x64",
            "url": "https://cdn.azul.com/zulu/bin/zulu18.30.11-ca-jdk18.0.1-linux_x64.tar.gz",
            "sha256": "975417f06145d3af06cb9b83fee2032f80fdae80766b1397157527c125bf00c1",
        },
    },
    "go": {
        "version": "1.18.3",
    },
    "gcs_expansions": {
        "configconnector-operator-yaml": {
            "doc": "Snapped from '1.88.0'",
            "purl": "pkg:generic/configconnector-operator-yaml@1.88.0?repository_url=storage.googleapis.com",
            "version": "1.88.0",
            "expansion": {
                "name": "configconnector-operator-yaml",
                "https_url": "https://storage.googleapis.com/configconnector-operator/1.88.0/release-bundle.tar.gz",
                "sha256": "ee1a35ca89528c2d6d99cd769f44da23665c06ba9565f8eb579ddc3fe7e4a4b6",
                "build_file_content": "exports_files(['operator-system/configconnector-operator.yaml'])",
            },
        },
        "spanner-emulator-archive": {
            "doc": "Snapped from '1.4.2'",
            "purl": "pkg:generic/spanner-emulator-archive@1.4.2?repository_url=storage.googleapis.com",
            "version": "1.4.2",
            "expansion": {
                "name": "spanner-emulator-archive",
                "https_url": "https://storage.googleapis.com/cloud-spanner-emulator/releases/1.4.2/cloud-spanner-emulator_linux_amd64-1.4.2.tar.gz",
                "sha256": "7048efb8708e0b2af98d84c9bd86ecb158b5663116c5dea789974d6a616f0e12",
                "build_file_content": "exports_files(['emulator_main'])",
            },
        },
    },
}
