filegroup(
    name = "all",
    srcs = glob(["*.txt"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "crds",
    srcs = glob(["*crd.yaml"]),
    visibility = ["//visibility:public"],
)
