filegroup(
    name = "minimal-openapi",
    srcs = ["minimal-openapi.yaml"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_crds",
    srcs = [
        "crd0.yaml",
        "crd1.yaml",
        "managedcertificates-crd.yaml",
        "minimal-crd.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "just_one_crd",
    srcs = ["minimal-crd.yaml"],
    visibility = ["//visibility:public"],
)
