java_binary(
    name = "SourceGenerator",
    srcs = ["SourceGenerator.java"],
    deps = [
        "@maven//:io_vavr_vavr",
        "@maven//:io_kubernetes_client_java_api",
        "@maven//:io_vavr_vavr",
        "@maven//:org_apache_commons_commons_compress",
        "@maven//:org_yaml_snakeyaml",
    ],
    visibility = ["//visibility:public"],
)
